
CREATE TABLE TEST(
    ID INT PRIMARY KEY,
    NAME VARCHAR(100),
    AGE INT NOT NULL
);

INSERT INTO TEST (ID, NAME, AGE) VALUES (1, 'Alice', 30);
INSERT INTO TEST (ID, NAME, AGE) VALUES (2, 'Bob', 25);
INSERT INTO TEST (ID, NAME, AGE) VALUES (3, 'Charlie', 35);

SELECT * FROM TEST;